title:             Kimu's Site
email:             kimu@kimu.me
description:       
author:            kimu
baseurl:           ""
url:               ""

# Social Profiles
github_username:   jcw1993

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
